#include "manta.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	KEYMAP(
		KC_Q, KC_W, KC_E, KC_R, KC_T, KC_1, KC_2, KC_3, KC_4, KC_5,
		KC_A, KC_S, KC_D, KC_F, KC_G, KC_6, KC_7, KC_8, KC_9, KC_0,
		KC_Z, KC_X, KC_C), LT(2, KC_V), LT(1, KC_B), SPC_FN3, KC_ENT, OSL(1), OSL(2), OSL(3), KC_MINS, KC_EQL),

	KEYMAP(
		KC_ENT, KC_BSPC, KC_TAB, KC_DEL, KC_TRNS,	KC_EXLM, KC_AT,	KC_HASH, KC_DLR, KC_PERC,
		KC_COLN,	KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN,
		KC_QUES, KC_GT, KC_LT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PLUS),

	KEYMAP(
		KC_HOME, KC_UP, KC_END, KC_PGUP, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
		KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,
		KC_LSFT, KC_LCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F11, KC_F12),

	KEYMAP(
		KC_P, KC_O, KC_I, KC_U, KC_Y, KC_PIPE, KC_DQUO, KC_TILD, KC_LCBR, KC_RCBR,
		KC_SCLN, KC_L, KC_K, KC_J, KC_H, KC_BSLS, KC_QUOT, KC_GRV, KC_LBRC, KC_RBRC,
		KC_SLSH, KC_DOT, KC_COMM, KC_M, KC_N, KC_SPC, KC_ESC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
};

void matrix_init_user(void) {
}

void matrix_scan_user(void) {
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
	return true;
}
